### ISSUE TITLE
Pick domain

### ISSUE THREAD

**Issue by romainl** [vim-advent-calendar/ideas#1]
* 24buffers.org
* 24dayswithvim.org
* avimchristmas.org
* xnoremas.org
* vim.rocks
* 24vims.org
* vimadvent.org

**Comment by romainl** [comment]
* 24vimstories.org
* vimstories.org
* vim.christmas
* vimways.org
* vimbeforexmas.org

**Comment by robertmeta** [comment]
Out of that list, and because vim.rocks is taken, I think the short-list should be two domains.  

 - vimways.org 

and 

 - vim.christmas

vimways.org is a great domain you could use year round and move your other writings to, while vim.christmas is a great sort of toy site we could reuse each year.  But it will end up costing us $150 a year to do that, ugh.

**Comment by robertmeta** [comment]
vimadvent.org could work as a cheaper drop in replacement for vim.christmas.

**Comment by romainl** [comment]
I like vimways.org the best. I agree that it could be used outside of the advent period.

**Comment by robertmeta** [comment]
The, I think we have decided, you want it on my server or you want to get a separate server setup?  If you want to move your writings to it, we can do long-term on your box, or you can have a perm account on my box.

**Comment by robertmeta** [comment]
If you want to be on my server, I would also give access to push to vi-improved for cross-posting if you wanted with stuff on vimways.org

**Comment by romainl** [comment]
@robertmeta we have vimways.org for 5 years. I'll close this issue.
